[package]
name = "kennel-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio = { version = "1.49.0", features = ["full", "signal"] }
tracing = "0.1.44"
